name: radoslaw
favicon: null
layout_spectrum: 0.7206949964165688
typography_spectrum: 0.3942753772716969
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d4d4f'
    - '#000000'
    - '#333333'
    - '#808080'
    - '#666666'
  brandStrength: 0.75
  lightness: 0.9654010343365371
  saturation: 0.8311631814576685
  rhythmicContrast: 0.0832442760001868
purpose: []
