name: radoslaw
favicon: null
layout_spectrum: 0.21001
typography_spectrum: 0.52249
title: radoslaw stankiewicz blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-43930216-6
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d4d4f'
    - '#000000'
    - '#333333'
    - '#808080'
    - '#666666'
  brandStrength: 0.75
  lightness: 0.9654010343365371
  saturation: 0.8311631814576685
  rhythmicContrast: 0.0832442760001868
purpose: []
